import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/video-streaming',
        'guides/gamepad-input',
        'guides/multi-controller',
        'guides/safety-heartbeat',
      ],
    },
    {
      type: 'category',
      label: 'React Components',
      items: [
        'react/overview',
        'react/teleoperate',
        'react/video-feed',
        'react/gamepad-controller',
        'react/multi-mode-layout',
        'react/stats-overlay',
      ],
    },
  ],
  // API sidebar is auto-generated by typedoc plugin
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
